backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/static"
public_folder: "/static"

collections:
  - label: "Site Data"
    name: "site data"
    files:
      - label: "carousel images"
        label_singular: "carousel image"
        name: "carousel images"
        file: "public/admin/data/carousel-images.json"
        fields:
          - name: carousel images
            label: images
            label_singular: image
            widget: list
            collapsed: true
            fields:
              - { label: "Image", name: "image", widget: "image" }
      - label: "About Us"
        name: "about us"
        file: "public/admin/data/aboutus.json"
        fields:
          - name: about us
            label: About Us
            widget: markdown
      - label: "Gallery Images"
        label_singular: "Gallery Image"
        name: "Gallery Images"
        file: "public/admin/data/gallery-images.json"
        fields:
          - name: gallery images
            label: images
            label_singular: image
            widget: list
            collapsed: true
            fields:
              - { label: "Image", name: "image", widget: "image" }
      - label: "Jobs"
        name: "Jobs"
        file: "public/admin/data/jobs.json"
        fields:
          - name: Jobs
            label: jobs
            label_singular: job
            widget: list
            collapsed: true
            fields:
              - { label: "jon", name: "job", widget: "jobwidget" }
