backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/static"
public_folder: "/static"

collections:
  - label: "Site Data"
    name: "site data"
    files:
      - label: "categories"
        label_singular: "category"
        name: "categories"
        file: "public/admin/data/categories.json"
        fields:
          - name: categories
            label: Categoriesconfig chane
            label_singular: category
            widget: list
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Featured Image", name: "thumbnail", widget: "image" }
              - {
                  label: "Images",
                  name: "images",
                  widget: "list",
                  field: { label: "Image", name: "image", widget: "image" },
                }
      - label: "homepage images"
        name: "homepage images"
        file: "public/admin/data/heroImages.json"
        fields:
          - name: images
            label: images
            widget: list
            collapsed: true
            field: { label: "Image", name: "image", widget: "image" }
      - label: "profile details"
        name: "profile details"
        file: "public/admin/data/profile.json"
        fields:
          - { label: "Header", name: "header", widget: "text" }
          - { label: "Details", name: "details", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }
          # - name: profile
          #   label: profile
          #   widget: object
          #   collapsed: true
          #   field:
